"""Packaged test data for :mod:`msgd.core`.

This subpackage exists so ``vectors.json`` ships inside the ``msgd`` wheel and is
locatable at runtime via ``importlib.resources.files("msgd.core.testdata")`` from both
the server and the CLI (and from a future TypeScript client's build tooling that reads
the installed file). ``vectors.json`` is the FROZEN cross-language JCS + hash golden
suite (ENG-56, the M0 exit-criterion artifact); it is generated by
``server/tests/generate_vectors.py`` and freeze-guarded by
``server/tests/test_vectors.py``.
"""
